server:
  port: 80

spring:
  application:
    name: hawk-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置注册中心进行路由功能
          lower-case-service-id: true # 将服务名称转小写
      routes:
        - id: hawk-diner
          uri: lb://hawk-diner
          predicates:
            - Path=/diner/**

        - id: hawk-oauth-server
          uri: lb://hawk-oauth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # /auth/oauth -> /oauth

        - id: hawk-voucher
          uri: lb://hawk-voucher
          predicates:
            - Path=/voucher/**

# 自配置放行白名单
secure:
  ignore:
    urls: # 配置白名单路径
      - /actuator/**
      - /auth/oauth/**
      - /diner/signin
      - /diner/verify-code/send
      - /diner/checkPhone
      - /diner/register
      - /voucher/add

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

#logging:
#  pattern:
#    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'